In [1]:
import pandas as pd
import numpy as np
import sys
sys.maxsize > 2**32 
# from sklearn.neighbors import NearestNeighbors

raiting = pd.read_csv('./ratings_drop.csv' , usecols=[ 'userId' , 'productId' , 'rating'] )
products = pd.read_csv('./products_join_categories.csv')
joinEdRaiting = pd.merge(raiting, products, on='productId', how='inner')
display(joinEdRaiting.head())
filtered = joinEdRaiting[joinEdRaiting.cat2==31]
print(filtered.shape)
display(filtered)


userId  productId  rating  Unnamed: 0  \
0    15905.0     452609     5.0      452609   
1    94522.0     452609     5.0      452609   
2   317087.0     452609     5.0      452609   
3  1329103.0     452609     5.0      452609   
4   502593.0     452609     5.0      452609   

                                                name       catIds  cat1  \
0  The Natural History Book: The Ultimate Visual ...  832,476,923   832   
1  The Natural History Book: The Ultimate Visual ...  832,476,923   832   
2  The Natural History Book: The Ultimate Visual ...  832,476,923   832   
3  The Natural History Book: The Ultimate Visual ...  832,476,923   832   
4  The Natural History Book: The Ultimate Visual ...  832,476,923   832   

  cat1_name  cat2 cat2_name   cat3 cat3_name  
0      图书音像   476      其它图书  923.0      进口图书  
1      图书音像   476      其它图书  923.0      进口图书  
2      图书音像   476      其它图书  923.0      进口图书  
3      图书音像   476      其它图书  923.0      进口图书  
4      图书音像   476      其它图书  923.0      进口图书

(62567, 12)


userId  productId  rating  Unnamed: 0  \
18479       5964.0     453957     1.0      453957   
18480      89094.0     453957     3.0      453957   
18481    1329597.0     453957     3.0      453957   
18482     489749.0     453957     3.0      453957   
18483      48449.0     453957     4.0      453957   
...            ...        ...     ...         ...   
7197445   267904.0     494124     5.0      494124   
7197446      303.0     494124     5.0      494124   
7197447     1588.0     494124     5.0      494124   
7197448   267901.0     494124     1.0      494124   
7197449    78977.0     494124     5.0      494124   

                                name        catIds  cat1 cat1_name  cat2  \
18479              富士 JV155 数码相机(黑色)  1128,31,1019  1128     手机/数码    31   
18480              富士 JV155 数码相机(黑色)  1128,31,1019  1128     手机/数码    31   
18481              富士 JV155 数码相机(黑色)  1128,31,1019  1128     手机/数码    31   
18482              富士 JV155 数码相机(黑色)  1128,31,1019  1128     手机/数码    31   
18483              富士 JV155 数码相机(黑色)  1128,31,1019  1128     手机/数码    31   
...                              ...           ...   ...       ...   ...   
7197445  Sony 索尼 DSC-TX30/B 数码相机 (黑)  1128,31,1019  1128     手机/数码    31   
7197446  Sony 索尼 DSC-TX30/B 数码相机 (黑)  1128,31,1019  1128     手机/数码    31   
7197447  Sony 索尼 DSC-TX30/B 数码相机 (黑)  1128,31,1019  1128     手机/数码    31   
7197448  Sony 索尼 DSC-TX30/B 数码相机 (黑)  1128,31,1019  1128     手机/数码    31   
7197449  Sony 索尼 DSC-TX30/B 数码相机 (黑)  1128,31,1019  1128     手机/数码    31   

        cat2_name    cat3 cat3_name  
18479        摄影摄像  1019.0      数码相机  
18480        摄影摄像  1019.0      数码相机  
18481        摄影摄像  1019.0      数码相机  
18482        摄影摄像  1019.0      数码相机  
18483        摄影摄像  1019.0      数码相机  
...           ...     ...       ...  
7197445      摄影摄像  1019.0      数码相机  
7197446      摄影摄像  1019.0      数码相机  
7197447      摄影摄像  1019.0      数码相机  
7197448      摄影摄像  1019.0      数码相机  
7197449      摄影摄像  1019.0      数码相机  

[62567 rows x 12 columns]

In [3]:
# chunksize = 30000
# final = pd.DataFrame()
# number = 0
# for dfTemp in pd.read_csv('./ratings_drop.csv', chunksize=chunksize , usecols=[ 'userId' , 'productId' , 'rating']):
#     dfTemp.drop_duplicates(subset=['userId', 'productId'], keep='first' , inplace =True )
#     dfTemp2 = dfTemp.pivot( index='userId' , columns='productId' , values="rating" ).fillna(0)
#     final = final.add(dfTemp2, fill_value=0)
#     del dfTemp2
#     number += dfTemp.shape[0]
#     print("processing the " + str(number) + " rows" )
    
# print(final.shape)
# display(final)

# print("output to the csv file...")
# final.to_csv('D:/step/raiting_matrix.csv', encoding="utf_8_sig")

raiting.sample(10)
raiting[raiting.productId]

userId  productId  rating
6468760  153381.0     104694     5.0
2387625    4238.0     437378     5.0
6422320  298488.0     101495     5.0
459238    25861.0      41299     5.0
1280054  235549.0      26316     4.0
7058945  690970.0     485119     5.0
849785   352501.0     382153     5.0
5765294   45746.0     194008     5.0
1295343  243288.0      27421     5.0
4652893   23397.0      83195     5.0

In [2]:
filtered.drop_duplicates(subset=['userId', 'productId'], keep='first' , inplace =True )
filtered_pivot = filtered.pivot( index='userId' , columns='productId' , values="rating" ).fillna(0)


D:\System\Users\mb95513\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [3]:
print(filtered_pivot.shape)
display(filtered_pivot.head())
print(filtered.shape)
display(filtered.head())

(20760, 1491)


productId  2134    2839    2995    3047    3400    4160    4344    4409    \
userId                                                                      
7.0           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9.0           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
22.0          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
34.0          0.0     5.0     0.0     0.0     0.0     0.0     0.0     0.0   
41.0          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

productId  4581    4587    ...  519487  519725  523276  523976  524470  \
userId                     ...                                           
7.0           0.0     0.0  ...     5.0     0.0     0.0     0.0     0.0   
9.0           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
22.0          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
34.0          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
41.0          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   

productId  524796  525225  525426  525450  525532  
userId                                             
7.0           0.0     0.0     0.0     0.0     0.0  
9.0           0.0     0.0     0.0     0.0     0.0  
22.0          0.0     0.0     0.0     0.0     0.0  
34.0          0.0     0.0     0.0     0.0     0.0  
41.0          0.0     0.0     0.0     0.0     0.0  

[5 rows x 1491 columns]

(62185, 12)


userId  productId  rating  Unnamed: 0               name  \
18479     5964.0     453957     1.0      453957  富士 JV155 数码相机(黑色)   
18480    89094.0     453957     3.0      453957  富士 JV155 数码相机(黑色)   
18481  1329597.0     453957     3.0      453957  富士 JV155 数码相机(黑色)   
18482   489749.0     453957     3.0      453957  富士 JV155 数码相机(黑色)   
18483    48449.0     453957     4.0      453957  富士 JV155 数码相机(黑色)   

             catIds  cat1 cat1_name  cat2 cat2_name    cat3 cat3_name  
18479  1128,31,1019  1128     手机/数码    31      摄影摄像  1019.0      数码相机  
18480  1128,31,1019  1128     手机/数码    31      摄影摄像  1019.0      数码相机  
18481  1128,31,1019  1128     手机/数码    31      摄影摄像  1019.0      数码相机  
18482  1128,31,1019  1128     手机/数码    31      摄影摄像  1019.0      数码相机  
18483  1128,31,1019  1128     手机/数码    31      摄影摄像  1019.0      数码相机

In [44]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
from scipy.sparse import csr_matrix

# query_index = np.random.choice(filtered_pivot.shape[0])
# display(query_index)

display(filtered_pivot)
# print(type(filtered_pivot.iloc[2]))
# display(filtered_pivot.head())
# display(filtered_pivot.iloc[2,:].to_numpy().reshape(1, -1))

productId  2134    2839    2995    3047    3400    4160    4344    4409    \
userId                                                                      
7.0           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9.0           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
22.0          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
34.0          0.0     5.0     0.0     0.0     0.0     0.0     0.0     0.0   
41.0          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...           ...     ...     ...     ...     ...     ...     ...     ...   
1415104.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1416510.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1417332.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1422991.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1422992.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

productId  4581    4587    ...  519487  519725  523276  523976  524470  \
userId                     ...                                           
7.0           0.0     0.0  ...     5.0     0.0     0.0     0.0     0.0   
9.0           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
22.0          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
34.0          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
41.0          0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
...           ...     ...  ...     ...     ...     ...     ...     ...   
1415104.0     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1416510.0     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1417332.0     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1422991.0     0.0     0.0  ...     0.0     0.0     0.0     4.0     0.0   
1422992.0     0.0     0.0  ...     0.0     0.0     0.0     5.0     0.0   

productId  524796  525225  525426  525450  525532  
userId                                             
7.0           0.0     0.0     0.0     0.0     0.0  
9.0           0.0     0.0     0.0     0.0     0.0  
22.0          0.0     0.0     0.0     0.0     0.0  
34.0          0.0     0.0     0.0     0.0     0.0  
41.0          0.0     0.0     0.0     0.0     0.0  
...           ...     ...     ...     ...     ...  
1415104.0     0.0     0.0     0.0     0.0     0.0  
1416510.0     0.0     0.0     0.0     0.0     0.0  
1417332.0     0.0     0.0     0.0     0.0     0.0  
1422991.0     0.0     0.0     0.0     0.0     0.0  
1422992.0     0.0     0.0     0.0     0.0     0.0  

[20760 rows x 1491 columns]

In [142]:
# us_canada_user_rating_pivot = us_canada_user_rating.pivot(index = 'bookTitle', columns = 'userID', values = 'bookRating').fillna(0)
filtered_matrix = csr_matrix(filtered_pivot.values)
model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(filtered_matrix)
NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

query_index = np.random.choice(filtered_pivot.shape[0])



# query_index = 1013638
distances, indices = model_knn.kneighbors(filtered_pivot.iloc[query_index, :].values.reshape(1, -1),
                                          n_neighbors=6)

display(filtered_pivot.iloc[query_index, :].values.max())

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(filtered_pivot.index[query_index]))
    else:
        display(np.argsort(filtered_pivot.iloc[indices.flatten()[i]].to_numpy())[::-1][0:5])
        display(np.sort(filtered_pivot.iloc[indices.flatten()[i]].to_numpy())[::-1][0:5])
#         print(filtered_pivot.iloc[indices.flatten()[i]].values.max())
        print('{0}: {1}, with distance of {2}:'.format(i, filtered_pivot.index[indices.flatten()[i]],
                                                       distances.flatten()[i]))

5.0

Recommendations for 476845.0:



array([954, 435, 499, 491, 492], dtype=int64)

array([3., 3., 0., 0., 0.])

1: 771074.0, with distance of 0.0:


array([954, 435, 499, 491, 492], dtype=int64)

array([1., 1., 0., 0., 0.])

2: 255016.0, with distance of 2.220446049250313e-16:


array([954, 435, 499, 491, 492], dtype=int64)

array([5., 5., 0., 0., 0.])

3: 13340.0, with distance of 2.220446049250313e-16:


array([954, 435, 499, 491, 492], dtype=int64)

array([5., 5., 0., 0., 0.])

4: 507770.0, with distance of 2.220446049250313e-16:


array([954, 435, 499, 491, 492], dtype=int64)

array([5., 5., 0., 0., 0.])

5: 383141.0, with distance of 2.220446049250313e-16:
